# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: v2ray/official
# Command to start on workspace startup (optional)
tasks:
  - before: echo "before stage" && sudo -s
    init: echo "init stage"
    command: echo "command stage"
  - command: top
    name: top
# Ports to expose on workspace startup (optional)
ports:
  - port: 3000-8999
    onOpen: notify
